---

# Tasks about Lynis installation from git repository

- name: 'Install prerequisites'
  become: True
  apt:
    name: "{{ item }}"
    cache_valid_time: "{{ lynis_apt_cache_valid_time }}"
    update_cache: "{{ lynis_apt_update_cache }}"
    state: 'present'
  with_items: "{{ lynis_git_prerequisites }}"


- name: 'Add hostkey if needed'
  become: True
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key }}"
    state: "{{ item.state }}"
  no_log: True
  with_items: "{{ lynis_git_host_keys }}"


- name: 'Clone Lynis git repository'
  become: True
  git:
    accept_hostkey: "{{ lynis_git_accept_host_key }}"
    dest: "{{ lynis_installation_dir }}"
    repo: "{{ lynis_git_repository }}"
    version: "{{ lynis_installation_version }}"


- name: 'Set files permission to root user'
  become: True
  file:
    path: "{{ lynis_installation_dir }}"
    owner: "{{ lynis_installation_owner }}"
    recurse: True
