---

# Main tasks file for lynis role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::lynis'
    - 'role::lynis::init'


# Include tasks to manage installation from git
- name: 'Manage Lynis install from git'
  include: "{{ role_path }}/tasks/install_from_git.yml"
  when: "{{ lynis_installation_type == 'git' }}"
  tags:
    - 'lynis::role'
    - 'lynis::install'


# Include tasks to manage crontab
- name: 'Manage crontab tasks'
  include: "{{ role_path }}/tasks/crontab_management.yml"
  when: "{{ lynis_manage_crontab }}"
  tags:
    - 'lynis::role'
    - 'lynis::config'
